spring:
  datasource:
    url: jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    name: gesela-api
security:
  jwt:
    token:
      secret-key: ${SECRETE_KEY}
